// <auto-generated />
namespace KhaoThiSoftware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_Column_DanhSachThi_SoBaoDanh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_Column_DanhSachThi_SoBaoDanh));
        
        string IMigrationMetadata.Id
        {
            get { return "202005030919503_Update_Column_DanhSachThi_SoBaoDanh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
