// <auto-generated />
namespace KhaoThiSoftware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alter_Table_Name_Roles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alter_Table_Name_Roles));
        
        string IMigrationMetadata.Id
        {
            get { return "202005070417146_Alter_Table_Name_Roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
